apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: wfd-eureka
spec:
  template:
    metadata:
      labels:
        app: whats-for-dinner
        tier: infrastructure
        component: eureka
    spec:
      containers:
      - name: eureka
        image: registry.ng.bluemix.net/whats_for_dinner/netflix-eureka:V1
        ports:
        - containerPort: 8761
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: wfd-eureka
