apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: wfd-eureka
spec:
  template:
    metadata:
      labels:
        app: whats-for-dinner
        tier: infrastructure
        component: eureka
    spec:
      containers:
      - name: eureka
        image: registry.ng.bluemix.net/whats_for_dinner/netflix-eureka:V1
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: whats-for-dinner
    tier: infrastructure
    component: eureka
spec:
  selector:
    app: whats-for-dinner
    tier: infrastructure
    component: eureka
  type: NodePort
  #type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8761
     nodePort: 31761
