apiVersion: v1
kind: Service
metadata:
  name: zuul
  labels:
    app: whats-for-dinner
    tier: infrastructure
    component: proxy
spec:
  selector:
    app: whats-for-dinner
    tier: infrastructure
    component: proxy
  type: NodePort
  #type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8080
     nodePort: 31080
