apiVersion: v1
kind: ConfigMap
metadata:
  name: wfd-zuul
  labels:
    app: whats-for-dinner
    tier: infrastructure
    component: proxy
data:
  application.yaml: |+
    server:
      port: 8080

    eureka:
      instance:
        hostname: zuul-proxy
        preferIpAddress: true
      client:
        serviceUrl:
          defaultZone: http://eureka:8761/eureka/
      server:
        renewalPercentThreshold: 0.32
        waitTimeInMsWhenSyncEmpty: 0

  bootstrap.yaml: |+
    spring:
      application:
        name: zuul-proxy
      cloud:
        config:
          uri:  http://config:8888/
          retry:
            initialInterval: 3000
            multiplier: 2.0
            maxInterval: 50000
            maxAttempts: 20
