apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: wfd-config
spec:
  template:
    metadata:
      labels:
        app: whats-for-dinner
        tier: infrastructure
        component: config
    spec:
      containers:
      - name: spring-config
        image: registry.ng.bluemix.net/whats_for_dinner/spring-config:V1
        ports:
        - containerPort: 8888
        env:
          - name: eureka_client_serviceUrl_defaultZone
            value: http://eureka:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: whats-for-dinner
    tier: infrastructure
    component: config
spec:
  selector:
    app: whats-for-dinner
    tier: infrastructure
    component: config
  type: NodePort
  #type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8888
     nodePort: 31888
