apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: whats-for-dinner
    tier: infrastructure
    component: config-server
spec:
  selector:
    app: whats-for-dinner
    tier: infrastructure
    component: config-server
  type: ClusterIP
  ports:
   - protocol: TCP
     port: 8888
     targetPort: 8888
