apiVersion: v1
kind: ConfigMap
metadata:
  name: wfd-dessert
  labels:
    app: whats-for-dinner
    tier: app
    component: dessert
data:
  application.yaml: |+
    server:
      port: 8080

    eureka:
      client:
        serviceUrl:
           defaultZone: http://eureka:8761/eureka/
      instance:
        hostname: dessert
        preferIpAddress: true

    wfd:
      dessert:
        order: 3
        type: dessert
        menu:
          - Chocolate Cake
          - Banoffee
          - Ice Cream

  bootstrap.yaml: |+
    spring:
      application:
        name: dessert-service
      cloud:
        config:
          uri: http://config:8888
          retry:
            initialInterval: 3000
            multiplier: 2.0
            maxInterval: 50000
            maxAttempts: 20
