apiVersion: v1
kind: Service
metadata:
  name: desserts
  labels:
    app: whats-for-dinner
    tier: app
    component: dessert
spec:
  selector:
    app: whats-for-dinner
    tier: app
    component: dessert
  type: ClusterIP
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
