apiVersion: v1
kind: ConfigMap
metadata:
  name: wfd-entree
  labels:
    app: whats-for-dinner
    tier: app
    component: entree
data:
  application.yaml: |+
    server:
      port: 8080

    eureka:
      client:
        serviceUrl:
           defaultZone: http://eureka:8761/eureka/
      instance:
        hostname: entrees
        preferIpAddress: true

    wfd:
      entree:
        order: 2
        type: dinner
        menu:
          - Steak
          - Chicken
          - Fish

  bootstrap.yaml: |+
    spring:
      application:
        name: entree-service
      cloud:
        config:
          uri: http://config:8888
          retry:
            initialInterval: 3000
            multiplier: 2.0
            maxInterval: 50000
            maxAttempts: 20
