apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: wfd-entree
spec:
  template:
    metadata:
      labels:
        app: whats-for-dinner
        tier: app
        component: entree
    spec:
      containers:
      - name: entree
        image: registry.ng.bluemix.net/whats_for_dinner/wfd-entree:V1
        ports:
        - containerPort: 8080
        env:
          - name: eureka_client_serviceUrl_defaultZone
            value: http://eureka:8761/eureka/
          - name: spring_cloud_config_uri
            value: http://config:8888/
          - name: PORT
            value: "8080"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: entrees
#  labels:
#    app: whats-for-dinner
#    tier: app
#    component: entree
#spec:
#  selector:
#    app: whats-for-dinner
#    tier: app
#    component: entree
  #type: LoadBalancer
#  type: NodePort
#  ports:
#   - protocol: TCP
#     port: 8080
