apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: wfd-appetizer
 labels:
   app: whats-for-dinner
   tier: app
   component: appetizer
spec:
  template:
    metadata:
      labels:
        app: whats-for-dinner
        tier: app
        component: appetizer
    spec:
      containers:
      - name: appetizer
        image: registry.ng.bluemix.net/whats_for_dinner/wfd-appetizer:V1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: wfd-appetizer
