apiVersion: v1
kind: Service
metadata:
  name: menu
  labels:
    app: whats-for-dinner
    tier: app
    component: menu
spec:
  selector:
    app: whats-for-dinner
    tier: app
    component: menu
  type: ClusterIP
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
