apiVersion: v1
kind: ConfigMap
metadata:
  name: wfd-ui
  labels:
    app: whats-for-dinner
    tier: app
    component: ui
data:
  application.yaml: |+
    server:
      port: 8080

    eureka:
      client:
        serviceUrl:
           defaultZone: http://eureka:8761/eureka/
      instance:
        hostname: dessert
        preferIpAddress: true

  bootstrap.yaml: |+
    spring:
      application:
        name: whats-for-dinner
      cloud:
        config:
          uri: http://config:8888
          retry:
            initialInterval: 3000
            multiplier: 2.0
            maxInterval: 50000
            maxAttempts: 20
