apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: whats-for-dinner
    tier: app
    component: ui
spec:
  selector:
    app: whats-for-dinner
    tier: app
    component: ui
  type: ClusterIP
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
