apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: wfd-eureka
spec:
  template:

    metadata:
      labels:
        app: whats-for-dinner
        tier: infrastructure
        component: eureka
    spec:
      containers:
      - name: eureka
        image: registry.ng.bluemix.net/whats_for_dinner/netflix-eureka:V1
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: whats-for-dinner
    tier: infrastructure
    component: eureka
  type: NodePort
  #type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8761
     nodePort: 31761
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: wfd-zuul
spec:
  template:
    metadata:
      labels:
        app: whats-for-dinner
        tier: infrastructure
        component: proxy
    spec:
      containers:
      - name: eureka
        image: registry.ng.bluemix.net/whats_for_dinner/netflix-zuul:V1
        ports:
        - containerPort: 8080
        env:
          - name: eureka_client_serviceUrl_defaultZone
            value: http://eureka:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    run: whats-for-dinner
    tier: infrastructure
    component: proxy
  type: NodePort
  ports:
   - protocol: TCP
     port: 80
     nodePort: 30080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: wfd-config
spec:
  template:
    metadata:
      labels:
        app: whats-for-dinner
        tier: infrastructure
        component: config
    spec:
      containers:
      - name: eureka
        image: registry.ng.bluemix.net/whats_for_dinner/spring-config:V1
        ports:
        - containerPort: 8888
        env:
          - name: eureka_client_serviceUrl_defaultZone
            value: http://eureka:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  selector:
    app: whats-for-dinner
    tier: infrastructure
    component: config
  #type: LoadBalancer
  type: NodePort
  ports:
   - protocol: TCP
     port: 8888
     nodePort: 31888
